---
- hosts: sample_server

  vars_files:
    - vars/sample.yml

  roles:
    - role: 'geerlingguy.composer'
      become: true
      become_user: root

- hosts: sample_server2

  vars_files:
    - vars/sample.yml

  roles:
    - role: 'geerlingguy.php'
      become: true
      become_user: root
